import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  // ── Public routes (accessibili senza login) ──────────────────────────────
  { path: 'faq',     loadComponent: () => import('./components/faq/faq').then(m => m.FaqComponent) },
  { path: 'guida',   redirectTo: 'faq', pathMatch: 'full' },
  { path: 'termini', loadComponent: () => import('./components/legal/legal').then(m => m.LegalDocComponent), data: { mode: 'terms' } },
  { path: 'privacy', loadComponent: () => import('./components/legal/legal').then(m => m.LegalDocComponent), data: { mode: 'privacy' } },
  { path: 'cookie',  loadComponent: () => import('./components/legal/legal').then(m => m.LegalDocComponent), data: { mode: 'cookies' } },
  { path: 'reset-password', loadComponent: () => import('./components/reset-password/reset-password').then(m => m.ResetPasswordComponent) },
  { path: 'verify-email',   loadComponent: () => import('./components/verify-email/verify-email').then(m => m.VerifyEmailComponent) },
  // ─────────────────────────────────────────────────────────────────────────
  { path: 'dashboard',    loadComponent: () => import('./components/dashboard/dashboard').then(m => m.DashboardComponent) },
  { path: 'prodotti',     loadComponent: () => import('./components/prodotti/prodotti').then(m => m.ProdottiComponent) },
  { path: 'clienti',      loadComponent: () => import('./components/clienti/clienti').then(m => m.ClientiComponent) },
  { path: 'fornitori',    loadComponent: () => import('./components/fornitori/fornitori').then(m => m.FornitoriComponent) },
  { path: 'agenti',       loadComponent: () => import('./components/agenti/agenti').then(m => m.AgentiComponent) },
  { path: 'ddt',          loadComponent: () => import('./components/ddt/ddt').then(m => m.DdtComponent) },
  { path: 'fatture',      loadComponent: () => import('./components/fatture/fatture').then(m => m.FattureComponent) },
  { path: 'fatture-elettroniche', loadComponent: () => import('./components/fatture-elettroniche/fatture-elettroniche').then(m => m.FattureElettronicheComponent) },
  { path: 'note-credito', loadComponent: () => import('./components/note-credito/note-credito').then(m => m.NoteCreditoComponent) },
  { path: 'ordini',       loadComponent: () => import('./components/ordini/ordini').then(m => m.OrdiniComponent) },
  { path: 'preventivi',   loadComponent: () => import('./components/preventivi/preventivi').then(m => m.PreventiviComponent) },
  { path: 'acquisti',     loadComponent: () => import('./components/acquisti/acquisti').then(m => m.AcquistiComponent) },
  { path: 'ordini-fornitore', loadComponent: () => import('./components/ordini-fornitore/ordini-fornitore').then(m => m.OrdiniFornitoreComponent) },
  { path: 'pagamenti',    loadComponent: () => import('./components/pagamenti/pagamenti').then(m => m.PagamentiComponent) },
  { path: 'scadenzario', loadComponent: () => import('./components/scadenzario/scadenzario').then(m => m.ScadenzarioComponent) },
  { path: 'scadenze-fiscali', loadComponent: () => import('./components/scadenze-fiscali/scadenze-fiscali').then(m => m.ScadenzeFiscaliComponent) },
  { path: 'magazzino',      loadComponent: () => import('./components/magazzino/magazzino').then(m => m.MagazzinoComponent) },
  { path: 'arrivi-merce',   loadComponent: () => import('./components/arrivi-merce/arrivi-merce').then(m => m.ArriviMerceComponent) },
  { path: 'vendita-banco',  loadComponent: () => import('./components/vendita-banco/vendita-banco').then(m => m.VenditaBancoComponent) },
  { path: 'report',       loadComponent: () => import('./components/report/report').then(m => m.ReportComponent) },
  { path: 'impostazioni', loadComponent: () => import('./components/impostazioni/impostazioni').then(m => m.ImpostazioniComponent) },
  { path: 'archivi',      loadComponent: () => import('./components/archivi/archivi').then(m => m.ArchiviComponent) },
  { path: 'listini',      loadComponent: () => import('./components/listini/listini').then(m => m.ListiniComponent) },
  { path: 'prima-nota',   loadComponent: () => import('./components/prima-nota/prima-nota').then(m => m.PrimaNotaComponent) },
  { path: 'fatture-ricorrenti', loadComponent: () => import('./components/fatture-ricorrenti/fatture-ricorrenti').then(m => m.FattureRicorrentiComponent) },
  { path: 'storico', loadComponent: () => import('./components/storico/storico').then(m => m.StoricoComponent) },
  { path: 'compliance', loadComponent: () => import('./components/compliance/compliance').then(m => m.ComplianceComponent) },
  { path: 'riconciliazione', loadComponent: () => import('./components/riconciliazione/riconciliazione').then(m => m.RiconciliazioneComponent) },
  { path: 'reports', loadComponent: () => import('./components/reports/reports').then(m => m.ReportsComponent) },
  { path: 'ecommerce', loadComponent: () => import('./components/ecommerce/ecommerce').then(m => m.EcommerceComponent) },
  { path: 'sdi-passive', loadComponent: () => import('./components/sdi-passive/sdi-passive').then(m => m.SdiPassiveComponent) },
  { path: 'ocr-fatture', loadComponent: () => import('./components/ocr-fatture/ocr-fatture').then(m => m.OcrFattureComponent) },
  { path: 'agenda', loadComponent: () => import('./components/agenda/agenda').then(m => m.AgendaComponent) },
  { path: 'portachiavi', loadComponent: () => import('./components/portachiavi/portachiavi').then(m => m.PortachiaviComponent) },
  { path: 'lavagna', loadComponent: () => import('./components/lavagna/lavagna').then(m => m.LavagnaComponent) },
  { path: 'aiuto',  loadComponent: () => import('./components/aiuto/aiuto').then(m => m.AiutoComponent) },
  { path: 'trial-expired', loadComponent: () => import('./components/trial-expired/trial-expired').then(m => m.TrialExpiredComponent) },
  { path: 'billing', loadComponent: () => import('./components/billing/billing').then(m => m.BillingComponent) },
  { path: 'account', loadComponent: () => import('./components/account/account').then(m => m.AccountComponent) },
  // Rotta sconosciuta → Dashboard. Senza questa, un indirizzo non valido lasciava
  // il guscio dell'app con l'area contenuti vuota: nessuna spiegazione, nessuna
  // via d'uscita. Deve restare l'ULTIMA voce dell'elenco.
  { path: '**', redirectTo: 'dashboard' },
];
